version: "3.9"

services:
  backend:
    build: .
    image: stockinfo:latest
    container_name: stockinfo-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
